pyang: fix import error
pyang complains
> error: module "neutron-networks" not found in search path

From rfc6020.txt
> 5.2.  File Layout
>
>    YANG modules and submodules are typically stored in files, one module
>    or submodule per file.  The name of the file SHOULD be of the form:
>
>      module-or-submodule-name ['@' revision-date] ( '.yang' / '.yin' )

Since it says "SHOULD", the file name convention is not mandatory.
But there isn't any good reason to have a file name
of neutron-network.yang (without lasting "s").

Change-Id: Ic6c98382fbbc5e073d5fc18e4a3dccdb4569face
Signed-off-by: Isaku Yamahata <isaku.yamahata@intel.com>
(cherry picked from commit 531666970eb1827b8d46cef4220105250381abfc)